<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Command line test"
           tests="3"
           failures="2"
           errors="0"
           skipped="0"
           time="0.093">
  <properties />
            <testcase name="tc01" time="0.004" classname="com.ai.api.testsuite.TestSuite">
                <failure type="java.lang.AssertionError"
                  message="expected [通过] but found [不通过]"
              >
<![CDATA[java.lang.AssertionError: expected [通过] but found [不通过]
  org.testng.Assert.fail(Assert.java:93)
  org.testng.Assert.failNotEquals(Assert.java:512)
  org.testng.Assert.assertEqualsImpl(Assert.java:134)
  org.testng.Assert.assertEquals(Assert.java:115)
  org.testng.Assert.assertEquals(Assert.java:189)
  org.testng.Assert.assertEquals(Assert.java:199)
  com.ai.api.support.dataDriver.Check.verifyResultDataColumnValue(Check.java:21)
  com.ai.api.testcase.TC01_test.runScript(TC01_test.java:45)
  com.ai.api.testsuite.TestSuite.tc01(TestSuite.java:26)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:209)
  org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:180)
  org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:221)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:657)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  com.ai.api.support.initTestNG.TestNGAdapter.runTestNG(TestNGAdapter.java:32)
  com.ai.api.testsuite.BaseSuite.main(BaseSuite.java:17)
]]>
      </failure>

          </testcase>
            <testcase name="tc01" time="0.002" classname="com.ai.api.testsuite.TestSuite">
                <failure type="java.lang.AssertionError"
                  message="expected [通过] but found [不通过]"
              >
<![CDATA[java.lang.AssertionError: expected [通过] but found [不通过]
  org.testng.Assert.fail(Assert.java:93)
  org.testng.Assert.failNotEquals(Assert.java:512)
  org.testng.Assert.assertEqualsImpl(Assert.java:134)
  org.testng.Assert.assertEquals(Assert.java:115)
  org.testng.Assert.assertEquals(Assert.java:189)
  org.testng.Assert.assertEquals(Assert.java:199)
  com.ai.api.support.dataDriver.Check.verifyResultDataColumnValue(Check.java:21)
  com.ai.api.testcase.TC01_test.runScript(TC01_test.java:45)
  com.ai.api.testsuite.TestSuite.tc01(TestSuite.java:26)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:209)
  org.springframework.test.context.testng.AbstractTestNGSpringContextTests.run(AbstractTestNGSpringContextTests.java:180)
  org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:221)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:657)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  com.ai.api.support.initTestNG.TestNGAdapter.runTestNG(TestNGAdapter.java:32)
  com.ai.api.testsuite.BaseSuite.main(BaseSuite.java:17)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="tc01" time="0.087" classname="com.ai.api.testsuite.TestSuite" />
      
</testsuite>
